services:
  db:
    container_name: compose-db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=tracker
    ports:
      - '5432:5432'
    networks:
      - api-network
  api:
    container_name: latest-api
    image: zackaryclark/strongman-tracker-api:latest
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - api-network
    environment:
      DB_PORT: 5432
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: tracker
networks:
  api-network: {}
