services:
  db:
    container_name: compose-db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=tracker
    ports:
      - '5432:5432'
    networks:
      - api-network
  api:
    container_name: latest-api
    image: zackaryclark/strongman-tracker-api:latest
    depends_on:
      - db
    ports:
      - '8082:8080'
    networks:
      - api-network
    environment:
      DB_PORT: 5432
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: tracker
      DB: tracker
      JWKS_URI: "https://dev-hhulso4duepd4br4.us.auth0.com/.well-known/jwks.json"
      AUDIENCE: "http://localhost:8082/graphql"
      ISSUER: "https://dev-hhulso4duepd4br4.us.auth0.com/"
networks:
  api-network: {}
